### ISSUE TITLE
Keyboard Type

### ISSUE THREAD

**Issue by rgomezp** [Ramiah-Viknesh/react-native-prompt-crossplatform#3]
Hello,
I would like to set the keyboard type for the prompt. How can I do this? Thanks so much

**Comment by Ramiah-Viknesh** [comment]
Hi @rgomezp you can set the keyboard type with the help of keyboardType prop.

example: 

```javascript
<Prompt
     title="Say something"
     placeholder="Enter Some Text"
     isVisible={this.state.visiblePrompt}
     keyboardType="number-pad"
  />
```
The various keyboard types with their screenshot is given in the below link 
https://lefkowitz.me/visual-guide-to-react-native-textinput-keyboardtype-options/


![Screenshot 2019-06-26 at 2 48 32 PM](https://user-images.githubusercontent.com/26657339/60167932-b46e9700-9821-11e9-8f52-22115d8a3c17.png)

**Comment by rgomezp** [comment]
Thanks for the response. Do you know how to get the keyboard to pop up along with the prompt (don't have to tap the text input field)?

**Comment by Ramiah-Viknesh** [comment]
you are welcome @rgomezp . The above can be achieved by setting the autoFocus prop to true.

example:

```javascript
<Prompt
     title="Say something"
     placeholder="Enter Some Text"
     isVisible={this.state.visiblePrompt}
     autoFocus={true}
  />
```

**Comment by rgomezp** [comment]
Awesome! Thank you again @Ramiah-Viknesh
